[tools]
darklua = "seaofvoices/darklua@0.12.1"
wally-package-types = "johnnymorganz/wally-package-types@1.3.1"
wally = "UpliftGames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.0"
stylua = "johnnymorganz/stylua@0.20.0"
selene = "kampfkarren/selene@0.26.1"
luau-lsp = "johnnymorganz/luau-lsp@1.27.1"
